version: '3'

services:
        reverse-proxy:
                image: traefik:v2.4
                ports:
                        - "80:80"
                        - "443:443"
                        #- "8080:8080"
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock:ro
                        - ./conf/:/etc/traefik/
                        - ./letsencrypt:/letsencrypt

networks:
        default:
                external:
                        name: traefik-proxy
